# persistent Volume for RPC Broker Cache
apiVersion: v1
kind: PersistentVolume
metadata:
  name: broker-cache-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  # Mount options: See https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/7/html/storage_administration_guide/s1-nfs-client-config-options
  mountOptions:
    - noexec
    - nosuid
    - sec=krb5p
  nfs:
    server: <NFS_SERVER_IP_OR_HOSTNAME>
    path: /artie/nfs/k3s-storage
    readOnly: false

  # Only schedule on nodes that have NFS access (node labeled with 'artie/storage=nfs')
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "artie/storage"
              operator: In
              values:
                - "nfs"
