# persistent Volume for Service Broker Cache
apiVersion: v1
kind: PersistentVolume
metadata:
  name: broker-cache-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  local:
    path: /var/lib/rancher/k3s/storage

  # Only schedule on the admin node (node labeled with 'artie/role=admin')
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "artie/role"
              operator: In
              values:
                - "admin"
            - key: "artie/storage"
              operator: In
              values:
                - "local"
