FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    cmake \
    gcc-arm-none-eabi \
    libnewlib-arm-none-eabi \
    build-essential \
    git \
    libstdc++-arm-none-eabi-newlib \
    python3 \
    wget \
    && \
    apt-get autoclean -y && apt-get autoremove -y

WORKDIR /pico
RUN mkdir -p /pico/src/
ARG PICO_RELEASE=1.5.1
RUN git clone --depth 1 --branch ${PICO_RELEASE} --recurse-submodules https://github.com/raspberrypi/pico-sdk.git
RUN git clone --depth 1 --branch sdk-${PICO_RELEASE} https://github.com/raspberrypi/pico-examples.git
RUN git clone --depth 1 --branch sdk-${PICO_RELEASE} https://github.com/raspberrypi/pico-extras.git
RUN git clone --depth 1 --branch sdk-${PICO_RELEASE} https://github.com/raspberrypi/pico-playground.git
ARG PICO_I2C_SLAVE_COMMIT=a25d1040950cdb4d37b50e05886c6195307f245c
RUN git clone https://github.com/vmilea/pico_i2c_slave && \
    git -C pico_i2c_slave checkout ${PICO_I2C_SLAVE_COMMIT} && \
    mv pico_i2c_slave/i2c_slave /pico/src/
RUN cp /pico/pico-sdk/external/pico_sdk_import.cmake /pico/src/pico_sdk_import.cmake

ENV PICO_SDK_PATH=/pico/pico-sdk
