name: driver-eyebrows-integration-test
networks:
  driver-eyebrows-itest:
    external: true

services:
  artie-rpc-broker:
    command: python -m src.main --port 18864
    container_name: eyebrows-itest-rpc-broker
    image: ${RPC_BROKER_TEST_IMAGE}
    expose:
      - 18864
    networks:
      - driver-eyebrows-itest
    environment:
      - ARTIE_RUN_MODE=integration
      - LOG_COLLECTOR_HOSTNAME=log-collector
      - LOG_COLLECTOR_PORT=5170
      - METRICS_SERVER_PORT=8090
      - ARTIE_LOG_LEVEL=DEBUG

  eyebrows-driver:
    command: python -m src.main /conf/mcu-fw.elf --port 18863
    container_name: eyebrows-itest-eyebrows-driver
    depends_on:
      - artie-rpc-broker
    image: ${EYEBROWS_TEST_IMAGE}
    expose:
      - 18863
    networks:
      - driver-eyebrows-itest
    environment:
      - ARTIE_RUN_MODE=integration
      - LOG_COLLECTOR_HOSTNAME=log-collector
      - LOG_COLLECTOR_PORT=5170
      - METRICS_SERVER_PORT=8090
      - RPC_BROKER_HOSTNAME=artie-rpc-broker
      - RPC_BROKER_PORT=18864
      - ARTIE_LOG_LEVEL=DEBUG

  artie-api-server:
    container_name: eyebrows-itest-api-server
    image: ${ARTIE_API_SERVER_TEST_IMAGE}
    depends_on:
      - eyebrows-driver
      - artie-rpc-broker
    expose:
      - 8782
    networks:
      - driver-eyebrows-itest
    environment:
      - ARTIE_RUN_MODE=integration
      - LOG_COLLECTOR_HOSTNAME=log-collector
      - LOG_COLLECTOR_PORT=5170
      - METRICS_SERVER_PORT=8090
      - PORT=8782
      - RPC_BROKER_HOSTNAME=artie-rpc-broker
      - RPC_BROKER_PORT=18864
      - ARTIE_LOG_LEVEL=DEBUG
