name: logging-integration-test
networks:
  logging-itest:
    external: true

services:
  log-collector:
    container_name: logging-itest-log-collector
    image: ${LOG_COLLECTOR_TEST_IMAGE}
    expose:
      - 5170
    networks:
      - logging-itest

  artie-service-broker:
    command: python -m src.main --port 18864
    container_name: logging-itest-service-broker
    image: ${ARTIE_SERVICE_BROKER_TEST_IMAGE}
    depends_on:
      - log-collector
    expose:
      - 18864
    networks:
      - logging-itest
    environment:
      - ARTIE_RUN_MODE=integration
      - LOG_COLLECTOR_HOSTNAME=log-collector
      - LOG_COLLECTOR_PORT=5170
      - METRICS_SERVER_PORT=8090
      - ARTIE_LOG_LEVEL=DEBUG

  eyebrows-driver:
    command: python -m src.main /conf/mcu-fw.elf --port 18863
    container_name: logging-itest-eyebrows-driver
    depends_on:
      - log-collector
      - artie-service-broker
    image: ${EYEBROWS_TEST_IMAGE}
    expose:
      - 18863
    networks:
      - logging-itest
    environment:
      - ARTIE_RUN_MODE=integration
      - LOG_COLLECTOR_HOSTNAME=log-collector
      - LOG_COLLECTOR_PORT=5170
      - METRICS_SERVER_PORT=8090
      - ARTIE_SERVICE_BROKER_HOSTNAME=artie-service-broker
      - ARTIE_SERVICE_BROKER_PORT=18864
      - ARTIE_LOG_LEVEL=DEBUG

  artie-api-server:
    container_name: logging-itest-api-server
    image: ${ARTIE_API_SERVER_TEST_IMAGE}
    depends_on:
      - eyebrows-driver
      - log-collector
      - artie-service-broker
    expose:
      - 8782
    networks:
      - logging-itest
    environment:
      - ARTIE_RUN_MODE=integration
      - LOG_COLLECTOR_HOSTNAME=log-collector
      - LOG_COLLECTOR_PORT=5170
      - METRICS_SERVER_PORT=8090
      - PORT=8782
      - ARTIE_SERVICE_BROKER_HOSTNAME=artie-service-broker
      - ARTIE_SERVICE_BROKER_PORT=18864
      - ARTIE_LOG_LEVEL=DEBUG
