name: driver-mouth-integration-test
networks:
  driver-mouth-itest:
    external: true

services:
  artie-service-broker:
    command: python -m src.main --port 18864
    container_name: mouth-itest-service-broker
    image: ${SERVICE_BROKER_TEST_IMAGE}
    expose:
      - 18864
    networks:
      - driver-mouth-itest
    environment:
      - ARTIE_RUN_MODE=integration
      - LOG_COLLECTOR_HOSTNAME=log-collector
      - LOG_COLLECTOR_PORT=5170
      - METRICS_SERVER_PORT=8090
      - ARTIE_LOG_LEVEL=DEBUG

  mouth-driver:
    command: python -m src.main /conf/mcu-fw.elf --port 18862
    container_name: mouth-itest-mouth-driver
    depends_on:
      - artie-service-broker
    image: ${MOUTH_TEST_IMAGE}
    expose:
      - 18862
    networks:
      - driver-mouth-itest
    environment:
      - ARTIE_RUN_MODE=integration
      - LOG_COLLECTOR_HOSTNAME=log-collector
      - LOG_COLLECTOR_PORT=5170
      - METRICS_SERVER_PORT=8090
      - SERVICE_BROKER_HOSTNAME=artie-service-broker
      - SERVICE_BROKER_PORT=18864
      - ARTIE_LOG_LEVEL=DEBUG

  artie-api-server:
    container_name: mouth-itest-api-server
    image: ${ARTIE_API_SERVER_TEST_IMAGE}
    depends_on:
      - mouth-driver
      - artie-service-broker
    expose:
      - 8782
    networks:
      - driver-mouth-itest
    environment:
      - ARTIE_RUN_MODE=integration
      - LOG_COLLECTOR_HOSTNAME=log-collector
      - LOG_COLLECTOR_PORT=5170
      - METRICS_SERVER_PORT=8090
      - PORT=8782
      - SERVICE_BROKER_HOSTNAME=artie-service-broker
      - SERVICE_BROKER_PORT=18864
      - ARTIE_LOG_LEVEL=DEBUG
