name: pubsub-integration-test
networks:
  pubsub-itest:
    external: true

services:
  artie-pubsub-broker:
    container_name: pubsub-itest-broker
    image: ${ARTIE_PUBSUB_BROKER_TEST_IMAGE}
    expose:
      - 9092
      - 9093
    networks:
      - pubsub-itest
    environment:
      - ARTIE_RUN_MODE=integration
      - LOG_COLLECTOR_HOSTNAME=log-collector
      - LOG_COLLECTOR_PORT=5170
      - METRICS_SERVER_PORT=8090
      - ARTIE_LOG_LEVEL=DEBUG
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://pubsub-itest-broker:9092
      - KAFKA_NUM_PARTITIONS=3

  artie-service-broker:
    command: python -m src.main --port 18864
    container_name: pubsub-itest-service-broker
    image: ${ARTIE_SERVICE_BROKER_TEST_IMAGE}
    depends_on:
      - artie-pubsub-broker
    expose:
      - 18864
    networks:
      - pubsub-itest
    environment:
      - ARTIE_RUN_MODE=integration
      - LOG_COLLECTOR_HOSTNAME=log-collector
      - LOG_COLLECTOR_PORT=5170
      - METRICS_SERVER_PORT=8090
      - ARTIE_LOG_LEVEL=DEBUG
      - ARTIE_PUBSUB_BROKER_HOSTNAME=pubsub-itest-broker
      - ARTIE_PUBSUB_BROKER_PORT=9092

  artie-test-sensor-service:
    command: python -m src.main --port 18865
    container_name: pubsub-itest-sensor-service
    image: ${ARTIE_TEST_SENSOR_SERVICE_TEST_IMAGE}
    depends_on:
      - artie-pubsub-broker
      - artie-service-broker
    expose:
      - 18865
    networks:
      - pubsub-itest
    environment:
      - ARTIE_RUN_MODE=integration
      - LOG_COLLECTOR_HOSTNAME=log-collector
      - LOG_COLLECTOR_PORT=5170
      - METRICS_SERVER_PORT=8090
      - ARTIE_LOG_LEVEL=DEBUG
      - ARTIE_SERVICE_BROKER_HOSTNAME=artie-service-broker
      - ARTIE_SERVICE_BROKER_PORT=18864
      - ARTIE_PUBSUB_BROKER_HOSTNAME=pubsub-itest-broker
      - ARTIE_PUBSUB_BROKER_PORT=9092

  artie-api-server:
    container_name: pubsub-itest-api-server
    image: ${ARTIE_API_SERVER_TEST_IMAGE}
    depends_on:
      - artie-service-broker
      - artie-pubsub-broker
    expose:
      - 8782
    networks:
      - pubsub-itest
    environment:
      - ARTIE_RUN_MODE=integration
      - LOG_COLLECTOR_HOSTNAME=log-collector
      - LOG_COLLECTOR_PORT=5170
      - METRICS_SERVER_PORT=8090
      - PORT=8782
      - ARTIE_SERVICE_BROKER_HOSTNAME=artie-service-broker
      - ARTIE_SERVICE_BROKER_PORT=18864
      - ARTIE_LOG_LEVEL=DEBUG
      - ARTIE_PUBSUB_BROKER_HOSTNAME=pubsub-itest-broker
      - ARTIE_PUBSUB_BROKER_PORT=9092
