name: telemetry-integration-test
networks:
  telemetry-itest:
    external: true

services:
  artie-service-broker:
    command: python -m src.main --port 18864
    container_name: telemetry-itest-service-broker
    image: ${SERVICE_BROKER_TEST_IMAGE}
    expose:
      - 18864
    networks:
      - telemetry-itest
    environment:
      - ARTIE_RUN_MODE=integration
      - LOG_COLLECTOR_HOSTNAME=log-collector
      - LOG_COLLECTOR_PORT=5170
      - METRICS_SERVER_PORT=8090
      - ARTIE_LOG_LEVEL=DEBUG

  eyebrows-driver:
    command: python -m src.main /conf/mcu-fw.elf --port 18863
    container_name: telemetry-itest-eyebrows-driver
    depends_on:
      - log-collector
      - artie-service-broker
    image: ${EYEBROWS_TEST_IMAGE}
    expose:
      - 18863
    networks:
      - telemetry-itest
    environment:
      - ARTIE_RUN_MODE=integration
      - LOG_COLLECTOR_HOSTNAME=log-collector
      - LOG_COLLECTOR_PORT=5170
      - METRICS_SERVER_PORT=8090
      - SERVICE_BROKER_HOSTNAME=artie-service-broker
      - SERVICE_BROKER_PORT=18864
      - ARTIE_LOG_LEVEL=DEBUG

  log-collector:
    container_name: telemetry-itest-log-collector
    image: ${LOG_COLLECTOR_TEST_IMAGE}
    expose:
      - 5170
    networks:
      - telemetry-itest

  metrics-collector:
    container_name: telemetry-itest-metrics-collector
    image: ${METRICS_COLLECTOR_TEST_IMAGE}
    depends_on:
      - eyebrows-driver
      - artie-api-server
      - artie-service-broker
    environment:
      - TEST_ENV=1
    networks:
      - telemetry-itest

  artie-api-server:
    container_name: telemetry-itest-api-server
    image: ${ARTIE_API_SERVER_TEST_IMAGE}
    depends_on:
      - eyebrows-driver
      - log-collector
      - artie-service-broker
    expose:
      - 8782
    networks:
      - telemetry-itest
    environment:
      - ARTIE_RUN_MODE=integration
      - LOG_COLLECTOR_HOSTNAME=log-collector
      - LOG_COLLECTOR_PORT=5170
      - METRICS_SERVER_PORT=8090
      - PORT=8782
      - SERVICE_BROKER_HOSTNAME=artie-service-broker
      - SERVICE_BROKER_PORT=18864
      - ARTIE_LOG_LEVEL=DEBUG
