# Default network policy to deny all ingress and egress traffic.
# Pod-to-pod communication is allowed within the same namespace.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: artie-default-network-policy
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: artie-default-network-policy
    {{- tpl (toYaml .Values.labels) . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {}
  egress:
  - to:
    - podSelector: {}
